### ISSUE TITLE
Implement 'life push' command

### ISSUE THREAD

**Issue by ChShersh** [kowainik/life-sync#12]
Copies all files from your machine to `dotfiles` repo and pushes this repo remotely.

**Comment by vrom911** [comment]
Probably the naming should be update?

**Comment by ChShersh** [comment]
@vrom911 Update doesn't clarify what exactly updates. There're two commands I want to implement:

1. `push`: copy all files specified in `.life` config and push them to remote repo.
2. `pull`: download latest version of remote repo and copy its content onto your local machine.

So you can either update local state (from remote) or remote state (from local). Alternative names would be:

1. `life upload`
2. `life download`.

Do you think they are better? I'm open to any other alternative proposals. Like `life up` or `life down` to make it shorter.

**Comment by vrom911** [comment]
No, now I see that `push` and `pull` are better for understanding 🙂
