### ISSUE TITLE
Refactor checking '.life' file and 'dotfliles' directory

### ISSUE THREAD

**Issue by ChShersh** [kowainik/life-sync#21]
I propose to have the following data type:

```haskell
data LifeExistence
    = Dead  -- ^ Sorry for my bad jokes
    | OnlyLife (Path Abs File)
    | OnlyRepo (Path Abs Dir)
    | Both (Path Abs File) (Path Abs Dir)
```

So then we can have `withExistingLife` function which checks for presence of these files globally and  write code like this:

```haskell
foo = withExistingLife >>= \case
  Dead -> ...
  OnlyLife lifeFile -> ...
  OnlyRepo repoDir -> ...
  Both lifeFile repoDir -> ...
```

What do you think?

**Comment by vrom911** [comment]
That's really helpful as I already used pattern matching like this several times.
