### ISSUE TITLE
Research (and implement if possible) whether there's an easy way to check that repo is synced

### ISSUE THREAD

**Issue by ChShersh** [kowainik/life-sync#26]
We don't want to commit if repo is not synced. I'm not sure whether it's possible or not to check it. But if possible (with `hub` or `git` for example) then it would be really great!

**Comment by vrom911** [comment]
https://gist.github.com/leroix/8829846
I found this nice solution but in `bash`. We could implement something similar.

**Comment by ChShersh** [comment]
@vrom911 Nice that solution exist! But need to think how to integrate it into our interface...
