### ISSUE TITLE
Show each called command?

### ISSUE THREAD

**Issue by ChShersh** [kowainik/life-sync#31]
I noticed that sometimes it might be useful to see what shell command is actually executed.

This can be easily done by patching this instance and printing called command (we only need to decide how to print commands):

https://github.com/kowainik/life-sync/blob/aef64e4e51b80b8b2b43973ed29e9fb7e1a1b0c4/src/Life/Shell.hs#L45-L46

What is more difficult, is implement this feature depending on some runtime value flag, like `--verbose`. But I think that showing each shell called command is a good default. By pattern-matching on `cmd` we can even show different cool unicode symbols for `git` command and other commands, like this:

```
★ git fetch origin master
✔ hub create
$ cd dotfiles
```

With better unicode symbols probably.

Possible alternatives (or simply other pretty symbols I found): 
`↪⇵ ⤽ ❉ λ ⚙ ⚒ 🌲 ⛓`

**Comment by vrom911** [comment]
Let's use ⚙for both `git` and `hub`?
