### ISSUE TITLE
Try to get github user name from `~/.gitconfig` if possible

### ISSUE THREAD

**Issue by chshersh** [kowainik/life-sync#36]
This can make UX more pleasant.

**Comment by SanchayanMaity** [comment]
```
readUserFromGitConfig :: IO Text
readUserFromGitConfig = do
    homeDir <- Dir.getHomeDirectory
    r <- readIniFile (homeDir <> "/.gitconfig")
    case r of
      Left err -> return $ T.pack err
      Right ini -> do
        let p = lookupValue "user" "name" ini
        case p of
          Left s -> return $ T.pack s
          Right t -> return t
```
I implemented the above currently. Do I understand correctly that this should be used in cloneRepo function to replace "owner"? Or at other places to?

**Comment by chshersh** [comment]
@SanchayanMaity I prefer to fetch `git` user name in a way it's already done in `hit-on`:

https://github.com/kowainik/hit-on/blob/0680c67d7c2edd24c931e1b9f7b5d5d19ce89f06/src/Hit/Git.hs#L287-L293

This issue assumes that `Owner` in the `Init` and `PullOptions` constructors of CLI options will become optional (using `Maybe`)

https://github.com/kowainik/life-sync/blob/c0e9aad0af75f5445b11ec4686b8ce05a3b78595/app/Options.hs#L20
https://github.com/kowainik/life-sync/blob/c0e9aad0af75f5445b11ec4686b8ce05a3b78595/app/Options.hs#L68-L72

If it's `Nothing` then the function should try to get the value from config.
