### ISSUE TITLE
Possibility to install the tool without stack/cabal

### ISSUE THREAD

**Issue by kilianovski** [kowainik/life-sync#47]
It will be nice if I can start using this tool on the machine without any Haskell infrastructure installed

**Comment by ChShersh** [comment]
@mitutee Thanks for your feedback! Indeed, that would be very convenient. What system are you on? I think it should be possible to distribute package on Ubuntu and MacOS without problems.

**Comment by mitutee** [comment]
@ChShersh I am using Windows for now :) But, anyway, I think even Ubuntu and MacOS options will engage non-Haskellers to use the tool

**Comment by vrom911** [comment]
:heavy_check_mark: Ubuntu (#91 )
:heavy_check_mark: MacOS (#90 )
