### ISSUE TITLE
Implement 'life sync' command

### ISSUE THREAD

**Issue by ChShersh** [kowainik/life-sync#7]
`life pull` followed by copying each file from `dotfiles` repository to your own machine.

**Comment by ChShersh** [comment]
Arrrgh, now I see that it's not clear why `life sync` does exactly this. My initial idea was to have commands

```
life sync pull
life sync push
life sync
```

where `life sync` is just `life sync pull >> life sync push`. But there's no sense in this sequence of commands. So maybe we should have

```
life pull
life pull sync
life push
life push sync
```

But I don't like this either...

**Comment by ChShersh** [comment]
Okay, I like the following option. Let it be these three commands:

```haskell
life sync pull
life sync push
life sync
```

And `life sync` will ask interactively what user wants to do. Makes sense? I was thinking about fancy API like check whether user pressed arrow up (for push = upload) or arrow down (for pull = download). But not sure whether it's possible or not...

**Comment by vrom911** [comment]
In my opinion to have command that does what already is possible with shorter command is a bit overhead. I'm about this two:
```shell
life sync pull
life sync push
```
So I propose to have only `life sync` with no arguments which will ask what to do (`pull` or `push`) explaining what exactly will be changed.

What do you think? Will it make more sense?

**Comment by ChShersh** [comment]
@vrom911 Yeah, I agree. It makes more sense. No need to have `life sync push` if there's already `life push`. We can implement just `life sync` which will ask what command to use and describe what they do.

**Comment by ChShersh** [comment]
Okay, after more discussion and more thinking 🤔 it became clear that such `life sync` command doesn't make sense. So let's close this issue until better use appear.
