### ISSUE TITLE
Apply weeder

### ISSUE THREAD

**Issue by vrom911** [kowainik/life-sync#72]

**Comment by vrom911** [comment]
Okay. `weeder` suggest to remove:
* `singleDirConfig`
* `createNewBranch`
* `doesBranchExist`

as unused functions. However, as we have plans on them, I would prefer to keep them for now.

**Comment by chshersh** [comment]
@vrom911 Excellent job! It's also great that you have a branch with `weeder` created, so we can easily return to this issue later if we want to cleanup everything again.
